[api_keys]
finnhub = "d3fq539r01qolknec6hgd3fq539r01qolknec6i0"

[auth]
username = "HXR"
password = "Rossph"

[connections.finance_db]
url="postgresql://postgres:F952fqUSGJ9Jh99d@db.jfozmxvuswolewlzkotm.supabase.co:5432/postgres"
