[api_keys]
finnhub = "d3fq539r01qolknec6hgd3fq539r01qolknec6i0"

[auth]
username = "HXR"
password = "Rossph"

[connections.finance_db]
url = "postgresql://finance_dashboard_db_tak8_user:FneNUHeEoMex9HTLxNDoLNpLBZ09FUq1@dpg-d3ue62ili9vc73c212q0-a.oregon-postgres.render.com/finance_dashboard_db_tak8"
