[api_keys]
finnhub = "d3fq539r01qolknec6hgd3fq539r01qolknec6i0"

[auth]
username = "HXR"
password = "Rossph"

[connections.finance_db]
url = "cockroachdb://marthala:JXeOUcwZtZNMavtAN41pdQ@wobbly-sandcat-17503.j77.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require"
